### ISSUE TITLE
Metadata extraction from Converter jdx/Bagit (input) to ChemSpectra generated jdx (output)

### ISSUE THREAD

**Issue by herrdivad** [ComPlat/chem-spectra-app#126]
Hi @baolanlequang ,

like we discussed yesterday, Nicole (@nicolejung) would like to have all Metadata from the Input (jdx) File to be saved on one of the ChemSpectra generated output jdx files.
You could start with the CV and AIF (SORPTION-DESORPTION MEASUREMENT) files because they are coming from the Converter and are already mostly standardized. But as far as I know every file converted from the Converter should have the Metadata on the same position (if there are any).

Please look at the pic and let me know, if you have questions:
 
![ChemSpectra_extractMetadata](https://github.com/ComPlat/chem-spectra-app/assets/113030128/f9b8acc7-1aaf-407c-9a90-9d0e334a5018)

**Comment by baolanlequang** [comment]
Closed by the PR https://github.com/ComPlat/chem-spectra-app/pull/158
