### ISSUE TITLE
Specifications for SEC (Size Exclusion Chromatography)

### ISSUE THREAD

**Issue by TasnimMehzabin** [ComPlat/chem-spectra-app#150]
- Curves need to be higher with normalization
- Display a table showing values of Mn, Mw, D (with Mp) in graph

**Comment by herrdivad** [comment]
Example Bagit File:
[SEC-ExFile.zip](https://github.com/ComPlat/chem-spectra-app/files/15246464/SEC-ExFile.zip)

Values (Mn, Mw, D, Mp) needed could be founded here:
![grafik](https://github.com/ComPlat/chem-spectra-app/assets/113030128/b578c27e-fdfb-416d-a7a2-3561b71e1e65) -> 
![grafik](https://github.com/ComPlat/chem-spectra-app/assets/113030128/eb8dec63-15a7-405b-92ec-404bad2197ae)
or also in data/table_01.jdx: 
![grafik](https://github.com/ComPlat/chem-spectra-app/assets/113030128/933a218b-9346-4875-83d6-f246eb6edbaf)

If possible, these values should please be vissible in the ChemSpectra Frontend and the downloaded png pics of each curve.

**Comment by baolanlequang** [comment]
Done by https://github.com/ComPlat/chem-spectra-app/pull/192
