### ISSUE TITLE
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chem-spectra-app#6]
Following your installation guide leads to an error with numpy:

```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
```

I am using a blank Ubuntu 21.04, the (outdated) version of Anaconda specified in your guide (2019.11) and numpy 1.16 as specified in requirements.txt.

Would your software work with a more recent version of numpy? I had 1.20.2 in mind ...

**Comment by baolanlequang** [comment]
You can get the newest version of Anaconda with this command:
`curl -O https://repo.anaconda.com/archive/Anaconda3-2020.11-Linux-x86_64.sh`

**Comment by ptrxyz** [comment]
Well, yes, and I understand that I could just change the numpy version in the requirements file and update my environment. But I wonder if your application would actually work with all the new versions or if it would break/deliver wrong results.

**Comment by ptrxyz** [comment]
Hm, if I might add a few thoughts:
It seems to me that numpy in the version you are using in your `requirements.txt` (that you install using pip) is pretty much not compatible with the version shipped with the anaconda release. This is, why one should not use `conda` and `pip` together. Is there a chance you would update the repo accordingly?

**Comment by baolanlequang** [comment]
We are using `conda` because the application need `rdkit`, which is installed from anaconda (https://www.rdkit.org/docs/Install.html), the other libraries in `requirements.txt` are installed by `pip`. So I'll check them and update them if necessary.

**Comment by ptrxyz** [comment]
Thanks! Would be great, since I updated numpy and "it works" (as in: there was no python exception or syntax errors), yet I do not have any real use-case and thus can't tell if it "
only works but produces wrong output" or if it "works but also produces wrong output"...

**Comment by baolanlequang** [comment]
Fixed in development branch, will be ready in next release.
