### ISSUE TITLE
Critical security issue in pillow

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chem-spectra-app#67]
Spectra app uses pillow 6.2 which has a critical security issue allowing arbitrary code execution. An update to version 9 or higher should fix this. Can we get this please?

![image](https://user-images.githubusercontent.com/209056/202727085-69d9cc78-02da-4065-ab71-7f9ab9883b26.png)

**Comment by baolanlequang** [comment]
Hi @ptrxyz , I'll look at it

**Comment by baolanlequang** [comment]
@ptrxyz , I was fixed at https://github.com/ComPlat/chem-spectra-app/releases/tag/0.10.17-patch.1

**Comment by baolanlequang** [comment]
Closed in https://github.com/ComPlat/chem-spectra-app/pull/69
