### ISSUE TITLE
CV Bagit: Only one spectra showable in Frontend App but multiple datas in Bagit

### ISSUE THREAD

**Issue by herrdivad** [ComPlat/chem-spectra-app#96]
Hi Team,

after uploading a CV RAW (.DTA) File or an already converted Bagit .zip Container, the App will only show one curve regardless if the Bagit contains 3 .jdx files. I've tested it on ELN Test Server http://193.196.38.77 and Repo (Repo Converter Profil is now deleted to cause no confusion.)
The Bug was not there a few days ago.

Thanks and best wishes
David

**Comment by herrdivad** [comment]
@baolanlequang can you please take a look because Nicole asked me to transport the CV Profiles to Repro and now I've seen this bug .

**Comment by herrdivad** [comment]
@baolanlequang sure of course.
[DHM-999-forHS4646_10mM-1mLVial_re2_no1_5mMFc.zip](https://github.com/ComPlat/chem-spectra-app/files/11002627/DHM-999-forHS4646_10mM-1mLVial_re2_no1_5mMFc.zip)

**Comment by herrdivad** [comment]
The Bug currently doesn't occure on https://complat-eln.ioc.kit.edu/ (however there is only an old CV converter profile)

**Comment by baolanlequang** [comment]
@herrdivad for the converter, I think you should contact Paggy.

**Comment by herrdivad** [comment]
Yeah I know it was just for testing and to distinguish the different versions.

**Comment by baolanlequang** [comment]
@herrdivad Can I close this issue?

**Comment by herrdivad** [comment]
@baolanlequang no or did you manged to fix it?
The bug still exists on Repro and Test Server, or not?
The Info with the Test ELN was just a hint for you to know which version works as intended and which not.

**Comment by herrdivad** [comment]
@baolanlequang okay thanks for the info.
@phuang26 could you please check the ChemSpectra versions on **Repro, Test ELN and Complat ELN?** I need to know which Version is newer and which one is **buggy**. And could you write the version number down here for Lan also to keep track.

**Comment by herrdivad** [comment]
@baolanlequang It seems that the ChemSpectra Version @phuang26 was asked to merge last week contains the bug. Paggy is now trying to revert the old version.
We checked the Server togetter and only Repro & Test ELN contains the newer patch with the bug.

**Comment by baolanlequang** [comment]
@herrdivad Can I close this issue?

**Comment by herrdivad** [comment]
Yes because the current version is working.
Thanks so far.

**Comment by herrdivad** [comment]
Hi @baolanlequang  and @phuang26 ,
sorry for the bad news, but the Bug is back at the Test Server since today. Yesterday or the day before it was not.
Did you do an update?

**Comment by herrdivad** [comment]
Version on Test ELN works again today. Thank you team!

**Comment by herrdivad** [comment]
Only Repo Version still have the Bug. Noticed today while testing CV Data.
Only one curve is shown.

**Comment by herrdivad** [comment]
Is now working again, thanks Team

**Comment by herrdivad** [comment]
Hi @phuang26 ,
Bug is back on Test Server after todays / yesterdays update.
Could you check please?
